version: '3.8'

services:
  api:
    build:
      context: ./api-service
      target: api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - REMINDER_LEAD_MINUTES=30
      # - EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: ./worker-service
      target: worker
    environment:
      - REDIS_URL=redis://redis:6379
      - REMINDER_LEAD_MINUTES=30
      # - EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}
    depends_on:
      - redis
      - api
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 