name: Worker Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'worker-service/**'
      - '.github/workflows/worker-service-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'worker-service/**'
      - '.github/workflows/worker-service-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          worker-service/package-lock.json
          worker-service/package.json

    - name: Install dependencies
      working-directory: worker-service
      run: npm ci

    - name: Run tests
      working-directory: worker-service
      run: npm test
      env:
        REDIS_URL: redis://localhost:6379
        REMINDER_LEAD_MINUTES: 30
        EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}

    - name: Run linting
      working-directory: worker-service
      run: npm run lint

    - name: Build
      working-directory: worker-service
      run: npm run build

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./worker-service
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/cooking-events-worker:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/cooking-events-worker:${{ github.sha }}
        platforms: linux/amd64,linux/arm64 